### ISSUE TITLE
Limit "Open days" in Availability and other features

### ISSUE THREAD

**Issue by sj49000** [calendso/calendso#128] opened 2021-05-02 08:48 UTC
Hi,
Thank you for this great project.

Is there a way to define days of availability ? For example, disable week-end days ?

Some features that would be great :
- manage shared mailbox calendar in Office 365
- Adding some fields in Event Type like phone number to send an SMS for recall

I can help in french translation and testing

**Comment by baileypumfleet** [comment] 2021-05-02 16:35
Duplicate of #78

**Closed by baileypumfleet** 2021-05-02 16:35 UTC
Labels: duplicate, enhancement
