### ISSUE TITLE
500 Internal Server Error on Cancelling and Rescheduling

### ISSUE THREAD

**Issue by resera** [calendso/calendso#546] opened 2021-09-01 13:12 UTC
### Issue Summary
I've tried to book a call from my other account from the testing purposes. Booking has been created successfully, but when I try to cancel or reschedule the booking by clicking the link in the email or in the calendar event that has been created, I'm getting these errors:

This one when trying to cancel:

> TypeError: Cannot read property 'startTime' of null
>     at getServerSideProps (/app/.next/server/pages/cancel/[uid].js:227:24)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)
>     at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97
>     at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142
>     at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)
>     at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:1088)
>     at async Server.render (/app/node_modules/next/dist/next-server/server/next-server.js:75:160)
>     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:58:672)

This one when trying to reschedule:

> TypeError: Cannot read property 'user' of null
>     at getServerSideProps (/app/.next/server/pages/reschedule/[uid].js:48:34)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:40:215)
>     at async /app/node_modules/next/dist/next-server/server/next-server.js:112:97
>     at async /app/node_modules/next/dist/next-server/server/next-server.js:105:142
>     at async Server.renderToHTMLWithComponents (/app/node_modules/next/dist/next-server/server/next-server.js:137:387)
>     at async Server.renderToHTML (/app/node_modules/next/dist/next-server/server/next-server.js:138:1088)
>     at async Server.render (/app/node_modules/next/dist/next-server/server/next-server.js:75:160)
>     at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:58:672)

Links are like these:

domain/cancel/xrgcqVZcA9ipZR5Gbk1CLi
domain/reschedule/xrgcqVZcA9ipZR5Gbk1CLi

**Comment by PeerRich** [comment] 2021-09-07 12:38
Hey @resera I believe this was fixed @KATT right?

**Comment by emrysal** [comment] 2022-01-12 13:57
Closing this; unable to reproduce and I believe long fixed.

**Closed** 2022-01-12 13:57 UTC
