### ISSUE TITLE
Login redirects to build specific vercel URL

### ISSUE THREAD

**Issue by SimonMayerhofer** [calendso/calendso#263] opened 2021-06-14 12:15 UTC
### Issue Summary
I deploy the app to Vercel on let's say https://calendso.domain.com/. After I login on the domain I get redirected to e.g. https://xxx-2ev0ar2q7-vercel-xxx.vercel.app/auth/login and I'm asked to login again.  If I then just navigate to https://calendso.domain.com I'm logged in and see the dashboard and everything works.
I set the `BASE_URL` environment variable.

### Technical details
* [Browser version](https://www.whatsmybrowser.org/b/9J625)
* Node.js version: 14

**Comment by Freundschaft** [comment] 2021-06-14 20:48
weird, it should be set according to

https://github.com/calendso/calendso/blob/main/next.config.js#L12

**Comment by SimonMayerhofer** [comment] 2021-06-14 21:27
I set it in the envirionment variables section in Vercel:

<img width="1118" alt="Screenshot 2021-06-14 at 23 27 01" src="https://user-images.githubusercontent.com/4314302/121961711-0d65cb80-cd68-11eb-9f89-662c356c3c57.png">

**Comment by Freundschaft** [comment] 2021-06-14 22:55
there seems to be an issue how the environment variables are read, but i havent been able to pin it down either

**Comment by emrysal** [comment] 2021-06-15 12:09
@Freundschaft Thanks, I'm investigating a potentially related issue #254 and this makes it seem like there's a side effect in the changes recently to implement `BASE_URL`.

**Comment by emrysal** [comment] 2021-06-15 16:15
My current belief is that this comes from the following line in the nextauth logic;

` baseUrlServer: (0, _parseUrl.default)(process.env.NEXTAUTH_URL_INTERNAL || process.env.NEXTAUTH_URL || process.env.VERCEL_URL).baseUrl,`

NEXTAUTH_URL seems to be unset, so the code in next.config.js has an issue on vercel.

**Comment by mihaic195** [comment] 2021-06-27 19:51
I can confirm this happens to me as well.

**Comment by emrysal** [comment] 2021-06-28 17:55
Hi all,

It was thought that automatically setting the NEXTAUTH_URL based on our own BASE_URL would decrease the manual configuration required for setup; but for now it seems that Vercel does not support dynamically updating environment variables. 

Some other config system is warranted here but whilst that solution is being investigated into I have added the findings of this issue & subsequent workaround to the `.env.example` file in https://github.com/calendso/calendso/pull/319. 

@mihaic195 For now this workaround is the recommended way to setup on Vercel.

**Comment by emrysal** [comment] 2021-07-03 17:53
Closing this as it looks like - for Vercel at least, NEXTAUTH_URL has to stay part of the .env - no way of fixing that one.

**Closed by emrysal** 2021-07-03 17:53 UTC
Labels: bug

**Comment by jpvalery** [comment] 2021-09-15 19:20
Just wanted to say that I encountered the same issue on Vercel and was able to get it going by adding `NEXTAUTH_URL` to the list of environment variables. Thanks @Freundschaft for the tip!
