### ISSUE TITLE
Sublinks are redirecting to login page.

### ISSUE THREAD

**Issue by asharabu** [calendso/calendso#254] opened 2021-06-10 07:18 UTC
Hi,
I have deployed the calendso URL and I could log in to the calendso URL but when I click on the buttons "Availability, Integrations, settings" its redirecting to the login page.

![image](https://user-images.githubusercontent.com/42669995/121481548-de5afd00-c9e9-11eb-93f1-7ad98474c979.png)

**Comment by emrysal** [comment] 2021-06-10 13:23
@asharabu I believe this may be due to an outdated database, have you ran `npx prisma db push`?

**Comment by asharabu** [comment] 2021-06-10 14:30
@emrysal Yes, I have done the command `npx prisma db push` before executing `yarn dev` command.

**Comment by asharabu** [comment] 2021-06-15 07:25
Any update on this?.

**Comment by emrysal** [comment] 2021-06-15 09:36
I'll do a deeper deepdive today, I have seen NaN show up before but this is upon session expiry, on the other hand I can see your avatar is set properly.

**Comment by emrysal** [comment] 2021-06-15 18:33
So I have reason to believe your session is initialised on the client, but not initialised serverside, what are you seeing when you output your session on both environments?

**Comment by matheusbaumgart** [comment] 2021-06-20 21:30
Same issue here :/

**Comment by asharabu** [comment] 2021-06-24 13:42
> So I have reason to believe your session is initialised on the client, but not initialised serverside, what are you seeing when you output your session on both environments?

What did you mean.? I am seeing the below output in the browser console when trying to take sublink like "Availability, Integrations, settings".
https://user-images.githubusercontent.com/42669995/121481548-de5afd00-c9e9-11eb-93f1-7ad98474c979.png

**Comment by szabi84** [comment] 2021-06-28 13:54
Same isse here.

Steps I made:
1. git pull (on main branch)
2. yarn install
3. npx prisma db push --preview-feature
4. yarn dev

And my dashboar looks exactly the same as the image attached by @asharabu

**Comment by emrysal** [comment] 2021-06-28 15:49
@szabi84 

So the trouble I'm facing is that I can't seem to reproduce this; I did notice a migration malfunction but the following route works for me:

1. git pull (main)
2. yarn install (this should run prisma, it did)
3. missing DB table (due to migration missing) fixed by `npx prisma migrate dev` (and PR'ed)
4. CP my env file from my dev env:
```bash
DATABASE_URL='postgres://'

BASE_URL='https://calendso.<host>'
NEXTAUTH_URL=https://calendso.<host>/api/auth

# BASE_PATH='/calendso'

GOOGLE_API_CREDENTIALS='{"web":{"client_id":"...","client_secret":"...","redirect_uris":[".."]}}'

MS_GRAPH_CLIENT_ID='xxxx'
MS_GRAPH_CLIENT_SECRET='xxxx'

EMAIL_SERVER_HOST='smtp.gmail.com'
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER='xxxx'
EMAIL_SERVER_PASSWORD='xxxx'
EMAIL_FROM='xxxx'
```
4. `insert into "users" (username, email, password) values ('alex', 'emrysal@...', '$2y$12$....');`
5. Login success.

Do you do anything differently?

**Comment by szabi84** [comment] 2021-06-30 07:03
@emrysal Thank you for your answer it helped. :+1: 
The problem was with my .env file, I think it was defined according to an older .env.example file. So the NEXTAUTH_URL was wrong and the BASE_URL was completely missing.

**Comment by emrysal** [comment] 2021-07-05 20:42
@asharabu Did you manage to apply the fix to your environment? I believe the root cause was the invalid `.env` which may have been due to invalid older README.

**Closed** 2021-07-22 11:06 UTC
